Amazon, IMDB & Yelp Review Classification

1. Importing the Data Sets

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
# Import Yelp Data Set
data_yelp = pd.read_csv("data/yelp_labelled.txt", sep='\t', header=None)

In [36]:
data_yelp
# Columns - Review & Sentiments

0  1
0                             Wow... Loved this place.  1
1                                   Crust is not good.  0
2            Not tasty and the texture was just nasty.  0
3    Stopped by during the late May bank holiday of...  1
4    The selection on the menu was great and so wer...  1
..                                                 ... ..
995  I think food should have flavor and texture an...  0
996                           Appetite instantly gone.  0
997  Overall I was not impressed and would not go b...  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

[1000 rows x 2 columns]

In [37]:
# Assign Column Names
column_name = ['Review', 'Sentiment']
data_yelp.columns = column_name

In [38]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [39]:
data_yelp.shape

(1000, 2)

In [40]:
# Import Amazon Data Set
data_amazon = pd.read_csv('data/amazon_cells_labelled.txt', sep='\t', header=None)

In [41]:
data_amazon.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [42]:
# Assign Columns Names to Amazon Data Set
data_amazon.columns = column_name

In [43]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [44]:
data_amazon.shape

(1000, 2)

In [45]:
# Import Imdb Data Set
data_imdb = pd.read_csv('data/imdb_labelled.txt', sep='\t', header=None)

In [46]:
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [47]:
data_imdb.columns = column_name

In [48]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [49]:
data_imdb.shape

(748, 2)

In [50]:
# Append all data into single data frame

In [51]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [52]:
data

Review  Sentiment
0                              Wow... Loved this place.          1
1                                    Crust is not good.          0
2             Not tasty and the texture was just nasty.          0
3     Stopped by during the late May bank holiday of...          1
4     The selection on the menu was great and so wer...          1
...                                                 ...        ...
2743  I just got bored watching Jessice Lange take h...          0
2744  Unfortunately, any virtue in this film's produ...          0
2745                   In a word, it is embarrassing.            0
2746                               Exceptionally bad!            0
2747  All in all its an insult to one's intelligence...          0

[2748 rows x 2 columns]

In [53]:
data.shape

(2748, 2)

In [55]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [57]:
# Check for null values
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [58]:
x = data['Review']
y = data['Sentiment']

2) Data Cleaning

In [59]:
# Here, we will remove stop words and punctuation
# Also, we will apply lemmatization

In [60]:
# Create a function to clean the data

In [61]:
import string

In [62]:
punct = string.punctuation

In [63]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [99]:
from spacy.lang.en.stop_words import STOP_WORDS

In [100]:
# list of stop words
stopwords = list(STOP_WORDS)

In [101]:
stopwords

['so',
 'even',
 'now',
 'whereupon',
 '‘s',
 'whose',
 'ten',
 'us',
 'though',
 'alone',
 'wherein',
 'keep',
 'doing',
 'few',
 'wherever',
 'anywhere',
 'whole',
 'i',
 'was',
 'except',
 'whether',
 'although',
 'a',
 'everywhere',
 'already',
 'became',
 'herein',
 'really',
 'of',
 'my',
 'further',
 'first',
 'hundred',
 'which',
 'enough',
 'its',
 'we',
 'sixty',
 'any',
 'them',
 'more',
 'three',
 'move',
 'formerly',
 'ours',
 'always',
 'four',
 'used',
 'therefore',
 'two',
 'he',
 'often',
 'others',
 'elsewhere',
 'thus',
 'no',
 'whither',
 'anyone',
 'under',
 'either',
 'nevertheless',
 'themselves',
 'say',
 'your',
 'or',
 'some',
 'out',
 'indeed',
 'per',
 'thence',
 'amongst',
 'against',
 '‘d',
 'whereafter',
 'much',
 'before',
 'rather',
 'anyway',
 'quite',
 'nor',
 'among',
 'six',
 'about',
 'up',
 'onto',
 'however',
 'give',
 'unless',
 'thru',
 'an',
 'top',
 'side',
 'mostly',
 'meanwhile',
 'their',
 'somehow',
 'therein',
 'please',
 'the',
 'are',


In [102]:
# Creating a function for data cleaning

In [152]:
import spacy
nlp = spacy.load(name = 'en_core_web_sm')

def text_data_cleaning(sentence):
    doc = nlp(sentence)
    
    tokens = [] # list of tokens
    for token in doc:
        if token.lemma_ != '-PRON-':
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    print('tokens: ',tokens) 
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens           
    

In [153]:
# If root form of the word is not pronoun then it is going to convert that into lower form 
# and if that word is proper noun, then we are directly taking lower form, because there is no lemma

In [154]:
text_data_cleaning("Hello all, it's a beautiful day outside there!")
# Stop Words and punctuation removed

tokens:  ['hello', 'all', ',', 'it', 'be', 'a', 'beautiful', 'day', 'outside', 'there', '!']


['hello', 'beautiful', 'day', 'outside']

Vectorization Feature Engineering (TF-IDF)

In [155]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [156]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)

In [109]:
classifier = LinearSVC()

3) Train the Model

In [110]:
#Splitting the dataset into train and test set

In [111]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [114]:
x_train.shape, x_test.shape

((2198,), (550,))

In [115]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

In [158]:
y_train.head()

2572    1
526     0
1509    0
144     1
2483    1
Name: Sentiment, dtype: int64

In [116]:
# Fit the x_train and y_train

In [118]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])
# It will do verctorization first and then does classification

In [119]:
clf.fit(x_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x000002711E59D310>)),
                ('clf', LinearSVC())])

In [120]:
# Predict the test results

In [121]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [162]:
y_pred = clf.predict(x_test)

In [123]:
# Confusion Matrix
confusion_matrix(y_test, y_pred)

array([[202,  77],
       [ 51, 220]], dtype=int64)

In [124]:
# Classification Report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.81      0.77       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [127]:
accuracy_score(y_test, y_pred)

0.7672727272727272

In [126]:
clf.predict(["Wow, I am learning natural language processing in fun fashion!"])

array([1], dtype=int64)

In [128]:
clf.predict(["It's hard to learn new things"])

array([0], dtype=int64)

In [129]:
clf.predict(["It's easy to learn new things"])

array([1], dtype=int64)